### ISSUE TITLE
Feature 1 - User can create personal account

### ISSUE THREAD

**Issue by semilee6557** [semilee6557/appointment-application#1]
## ⚙️ Feature 1
​
> ##### What capability will users have when this feature is merged?
​
​User can create personal account

## �� Functionality
​
> ##### A description of how the application will work from the perspective of the user.
​​
User can create new account with their email and new password.
If email is exist, user cannot make new account.
If password is not matched, user cannot make new account.
After sign up, user will see page with registration link.

## ��️ Wireframes
​
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
​

![Screen Shot 2021-05-04 at 7 41 25 PM](https://user-images.githubusercontent.com/61755795/117091802-48a8bf80-ad11-11eb-8e52-93830260e9e3.png)
​
![Screen Shot 2021-05-04 at 7 56 53 PM](https://user-images.githubusercontent.com/61755795/117092529-5fe8ac80-ad13-11eb-8046-d1ef8f61c916.png)

![Screen Shot 2021-05-04 at 7 41 43 PM](https://user-images.githubusercontent.com/61755795/117091800-47779280-ad11-11eb-8430-eab83fba8524.png)
## ✅ Task List
​
> ##### Commit checklist for tasks needed to complete the feature.
​
- [x] Create API endpoint to register user.
- [x] Make sure that email is not registered before.
- [x] Make sure password is contained requirement.
- [x] Make sure password is matching with confirm password.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
