### ISSUE TITLE
Feature 2 - User can fill out registration form

### ISSUE THREAD

**Issue by semilee6557** [semilee6557/appointment-application#2]
## ⚙️ Feature 2
​
> ##### What capability will users have when this feature is merged?
​

​User can fill out registration form

## �� Functionality
​
> ##### A description of how the application will work from the perspective of the user.
​

User can fill out their medical history and demographic information. 

User can upload files.

## ��️ Wireframes
​
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
​

​
![Screen Shot 2021-05-04 at 8 14 21 PM](https://user-images.githubusercontent.com/61755795/117093306-6841e700-ad15-11eb-8965-4ce7ee1a3808.png)
![Screen Shot 2021-05-04 at 8 14 31 PM](https://user-images.githubusercontent.com/61755795/117093308-68da7d80-ad15-11eb-8a30-7692e21e42b4.png)
![Screen Shot 2021-05-04 at 8 14 45 PM](https://user-images.githubusercontent.com/61755795/117093309-69731400-ad15-11eb-8cdb-0e73a175e446.png)

## ✅ Task List
​
> ##### Commit checklist for tasks needed to complete the feature.
​
- [ ] Create API endpoint to registration form database.
- [ ] Make sure that user can upload multiple files.
- [ ] Make sure that user can cancel to fill out registration.

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
