### ISSUE TITLE
Feature 3: User can log in

### ISSUE THREAD

**Issue by semilee6557** [semilee6557/appointment-application#3]
​
## ⚙️ Feature
​
> ##### What capability will users have when this feature is merged?
​

​User can log in

## �� Functionality
​
> ##### A description of how the application will work from the perspective of the user.
​

​User can log in with their email and password.
If user is new, user can link create new account to make new account. 

## ��️ Wireframes
​
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
​

​
![Screen Shot 2021-05-04 at 8 19 26 PM](https://user-images.githubusercontent.com/61755795/117093541-19e11800-ad16-11eb-936e-a1f76693e91b.png)
![Screen Shot 2021-05-04 at 8 19 36 PM](https://user-images.githubusercontent.com/61755795/117093542-1a79ae80-ad16-11eb-8579-bad5f3da6691.png)
![Screen Shot 2021-05-04 at 8 19 43 PM](https://user-images.githubusercontent.com/61755795/117093550-1e0d3580-ad16-11eb-9279-5c06b02da92b.png)

## ✅ Task List
​
> ##### Commit checklist for tasks needed to complete the feature.
​
- [ ] Get user's data from server to log-in.
- [ ] Make sure that if user's id and password is matching, "Sign-in" in menu will be change to "Logout".
- [ ] Make sure that once user is log-in, home page will be changed.
- [ ] Make sure that if it is not matching, alert message to user.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
